### PR TITLE
use ynh_port_available in ynh_find_port

### PR DESCRIPTION
**Pull request by kay0u**
## The problem

Duplicate the code. `ynh_port_available` may not work on ipv6

## Solution

Apply the patch to `ynh_port_available` and use it in `ynh_find_port`

## PR Status

...

## How to test

...

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Not a hot fix, and not even to be merged in unstable yet.
This PR aims to #947 for now

**Comment by alexAubin** [comment]
Ah yes indeed. Shall we click the merge button to go into clean_helpers ? :P

**Comment by maniackcrudelis** [comment]
Really ? You're brave enough to do that !?

**Comment by alexAubin** [comment]
Watch me ! :smiling_imp:

**Comment by maniackcrudelis** [comment]
Oh damn !!! He did it !!!

**Pull request merged**
