### PR TITLE
Add the internal helper ynh_handle_getopts_args

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## The problem

As said here, https://github.com/YunoHost/yunohost/pull/455, using positional arguments could be a problem when we're adding new options to a helper.

## Solution

Use a helper to allow to use easily getopts to manage arguments.

## PR Status

Ready to be reviewed.

## How to test

Have a look to [experimental helpers](https://github.com/YunoHost-Apps/Experimental_helpers), which already use getopts.

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by alexAubin** [comment]
0jnxn

**Comment by Josue-T** [comment]
Good idea :+1: 

When do you think about implementing this in all official helper ?

**Comment by maniackcrudelis** [comment]
After this PR will be merged ;)

**Comment by alexAubin** [comment]
I'm marking this a ready to merge and will merge in 2~3 days if no opposition

**Comment by alexAubin** [comment]
Actually fuck that /o\ We have 4 agreements + the author and I don't think we'll get more feedback on this, so yolomergin' ¯\\\_(ツ)\_/¯

**Pull request merged**
