### PR TITLE
Common ssh keys operations support

### PR DESCRIPTION
**Pull request by Psycojoker**
Hello,

The idea of this work is to integrate all common ssh keys operation into yunohost.

2 mains interests from here are:

- `yunohost ssh user enable-ssh` to allow a user to login with ssh
- provide all those operations in the web interface for people that don't know how to do that in cli (or are lazy)

I know that ssh key generation is also needed for federation or backup stuff.

This is a full working prototype, there is probably cleaning that needs to be done in addition to more testing and probably edge cases and some TODOs.

New commands (so we can bikeshed on the command names :yum:):

- `yunohost ssh user list` list all users with ssh related informations (access is enabled for eg)
- `yunohost ssh user allow-ssh $username` allow a user to login in ssh
- `yunohost ssh user disallow-ssh $username` inverse
- `yunohost ssh root-login status` show if root can log in ssh (`PermitRootLogin` stuff)
- `yunohost ssh root-login enable/disable`
- `yunohost ssh key list $username` list ssh keys of the users (only `.pub` files for now, don't know if that should include private files)
- `yunohost ssh key add $username` (`-a` to specify algo, `-n` for a key name) generate a new ssh key pair using `ssh-keygen`
- `yunohost ssh key import $username -u $public_key -i $private_key` import a ssh key pair (from another computer for eg)
- `yunohost ssh key remove $username -n $key_name`
- `yunohost sh authorized-keys list $username` parse and list the content of `~/.ssh/authorized_keys` (assume that a comment before a key is the title of the key)
- `yunohost ssh authorized-keys add $username -k $key` (`-c` to add a comment) add a key (with a comment before) to `~/.ssh/authorized_keys`
- `yunohost ssh authorized-keys remove $username -k $key`

### CODE REVIEW

**Comment by zamentur** [comment]
"yunohost ssh key add $username" => I suggest to rename as "yunohost ssh key create $username" .

Example of usage for "yunohost authorized-keys add":
yunohost authorized-keys add $username -k "ssh-ed25519 AAAAC3N...752CyXG"
yunohost authorized-keys add $username -k 'command="borg serve --restrict-to-path /home/USER/backup",no-pty,no-agent-forwarding,no-port-forwarding,no-X11-forwarding,no-user-rc ssh-ed25519 AAAAC3...J4RQ7ryaUi root@example.com'

**Comment by Psycojoker** [comment]
> "yunohost ssh key add $username" => I suggest to rename as "yunohost ssh key create $username" .

I understand why you want that (and that seems indeed more intuitive) but we already uses `add` nearly everywhere, except for user creation (and backup apparently) and that create an incoherence in the CLI interface.

I would prefer that we either uses `add` or `create` everywhere to keep the same semantic as often as possible (and `add` seems more generic than `create`), I think that this will improve the CLI API experience if only a small set of words need to be remembers and are used everywhere.

**Comment by alexAubin** [comment]
Risking to sound like the annoying guy here :confused: .. But I have these three points of concern about the general design : 

- I'm really not comfortable with the idea that the root/admin would or could manage his users private/public key to *others* servers (i.e. what the `yunohost users key` intends to). I don't really see a use case like "admin of server A wants to add a key to user Alice such that she can connect to unrelated server B" ? Except in very specific cases, imho, a user should never store a private key that gives access to another server .. on a server he doesn't own/administrate himself. And if he does, that should be his own business because there should at least be a passphrase associated to the private key.
- I'd really like if we could avoid to create a new category. Imho it would be more logical to add a `ssh` subcategory to `user`, to have `yunohost user ssh` with actions like `allow`/`disallow`, `add-key`/`remove-key`/`list-keys` (implicitly being authorized keys, because imho that should be the only kind of key the admin manages about his users :/)
- Move the root-login toggle to a global settings.

**Comment by Psycojoker** [comment]
> I'm really not comfortable with the idea that the root/admin would or could manage his users private/public key to others servers (i.e. what the yunohost users key intends to). I don't really see a use case like "admin of server A wants to add a key to user Alice such that she can connect to unrelated server B" ? Except in very specific cases, imho, a user should never store a private key that gives access to another server .. on a server he doesn't own/administrate himself. And if he does, that should be his own business because there should at least be a passphrase associated to the private key.

I understand why you are not comfortable with that because the usages you have in mind are indeed bad, but beside those I think that they are several legitimate usages worth it:

* I want to manage the keys of my own user on my server
* I need to generate a key for a user to give him access to another server and I want to have control on that key (for automated process for example)
* I need keys for automated process like backup
* I use several users on my own for several different activities and I want to easily managed all those keys

And already doing bad operation is so freaking easy that I don't see how integrating ssh management in core would make any difference in that regard and I think that the possibility to do those operations is worth it.

All of that make me think that integrating something like "ssh-copy-id" could be great but that will be for another PR.

> I'd really like if we could avoid to create a new category. Imho it would be more logical to add a ssh subcategory to user, to have yunohost user ssh with actions like allow/disallow, add-key/remove-key/list-keys

I have no strong opinion on that, I think that the idea of not wanting to add new categories is not based on solid argument but more on "what if one day" and I generally think that having several categories is better than merging everything together because you have a way cleaner organisation and way more easier discovery of what possibilities are available.

But if it's important for you why not.

> Move the root-login toggle to a global settings.

Right, I actually wanted to do that but totally forgot because I didn't wrote down what I wanted to do /o\

**Comment by Psycojoker** [comment]
I've started splitting this PR into https://github.com/YunoHost/yunohost/pull/403 and https://github.com/YunoHost/yunohost/pull/404

**Comment by alexAubin** [comment]
[Semi-automatic message] 
Trying to clean PR which are opened and inactive since more than 6 months ~ 1 year ... I propose to close this PR and keep it in the "Horizon" milestone in case somebody wants to take care of it later. But in the meantime there's no point in keeping all of these opened if there's no indication that someone might work on this soon.

**Pull request closed without merging**
