### PR TITLE
[FIX] app actions

### PR DESCRIPTION
**Pull request by kay0u**
## The problem

[admin panel use app_id](https://github.com/YunoHost/yunohost-admin/blob/stretch-unstable/src/views/app/app_actions.ms#L14)

## Solution

Add app_id

## PR Status

...

## How to test

...

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by kay0u** [comment]
I did that because of this: https://github.com/YunoHost/yunohost/blob/4e920c3040f9df7f0e95ed5fb59f4bcb88dade39/src/yunohost/app.py#L1596

It is duplicated for the config panel. (And I'm afraid of breaking something :P)

**Comment by alexAubin** [comment]
I think you mean : https://github.com/YunoHost/yunohost-admin/blob/stretch-unstable/src/views/app/app_actions.ms#L14

so I think I understand the issue ;) But I would rather just change the app_actions.ms file (app_id -> app) rather than duplicate the info :s

**Comment by kay0u** [comment]
No I mean that this information is already duplicated for the config panel, but I can change app_actions.ms, it would be clearer

https://github.com/YunoHost/yunohost/blob/4e920c3040f9df7f0e95ed5fb59f4bcb88dade39/src/yunohost/app.py#L1596-L1597

**Comment by alexAubin** [comment]
Thanks !

**Pull request closed without merging**
