### PR TITLE
[enh] More precise for regenconf --force when a file has changed sinc…

### PR DESCRIPTION
**Pull request by julienmalik**
…e last generation

### CODE REVIEW

**Comment by julienmalik** [comment]
do not merge yet.

actually the message is not that helpful, since we do not provide any way to "apply modification manually" : users can't apply their modifications unless they first run with --force. and then they need the old diff around, or they need to remember what they did to their file...

**Comment by julienmalik** [comment]
see also https://dev.yunohost.org/issues/172

**Comment by julienmalik** [comment]
IMHO we should be ultra-verbose in that case and better drive users into how to reapply their custom modifications over the new yunohost-maintainer version.

regenconf --force should :
- check if it needs to save the  user-modified file (already done ?)
- save the current user-modified file (already done I think in /home/yunohost.backup/conffiles)
- report the location of the saved user-modified file explicitely in the logs
- show diff between the user-modified file and the new "maintainer version."

**Comment by julienmalik** [comment]
follow-up in https://dev.yunohost.org/issues/172

**Comment by jeromelebleu** [comment]
Not valid anymore due to https://github.com/YunoHost/yunohost/pull/138.

**Pull request closed without merging**
