### PR TITLE
Update Metronome configuration file to v3.11 standard

### PR DESCRIPTION
**Pull request by maranda**
## The problem
Some now wanted features aren't loaded because Metronome uses a very old file

## Solution
Conform configuration file to latest v3.11 release file, Metronome v3.11.x is best package or Metronome might throw a few (non-fatal) errors on startup

- [ ] Principle agreement 1/2: @M5oul
- [ ] Quick review 0/1:
- [x] Simple test 1/1: @M5oul 
- [x] Deep review 1/1: @M5oul

### CODE REVIEW

**Comment by M5oul** [comment]
To test it on a production instance:
```bash
cd /usr/share/yunohost/templates/metronome
rm metronome.cfg.lua
wget https://raw.githubusercontent.com/YunoHost/yunohost/19120cfa60c02303eb7a0632ffb10f0ad5c48b37/data/templates/metronome/metronome.cfg.lua
sudo yunohost service regen-conf metronome --force
```

**Comment by M5oul** [comment]
I don’t think:
```bash
sudo yunohost service regen-conf metronome --force
```
will happen.
Is there a way to run it automatically. Using a migration script?
It may erase some custom configurations.

**Comment by alexAubin** [comment]
>I don’t think:
>
>`sudo yunohost service regen-conf metronome --force`
>
>will happen.
>Is there a way to run it automatically. Using a migration script?
>It may erase some custom configurations.

Is the `--force` needed here ? Won't it be regenerated by a simple regen-conf (which is done at every regular upgrade of the yunohost package) as long as the conf was not manually edited ?

**Comment by M5oul** [comment]
> Is the --force needed here ? Won't it be regenerated by a simple regen-conf (which is done at every regular upgrade of the yunohost package) as long as the conf was not manually edited ?

Good question. Without the `--force` it wasn’t working. May be because I did change the configuration file. It could be a security avoiding custom configuration to be erased.

In case someone did modify this file, they won’t profit from all Metronome’s features.

**Comment by M5oul** [comment]
Ok, looks good to merge soon.
Concerning the regen-conf, I propose to notify people in the release annoncement that they can regenerate Metronome configuration with upper command to enable all the features.

**Comment by alexAubin** [comment]
Tested today and a regular regenconf was enough.

Yolomergin' /o/

**Pull request merged**
