### PR TITLE
[fix] add all users in visitors

### PR DESCRIPTION
**Pull request by kay0u**
## The problem

https://github.com/YunoHost/issues/issues/1485
https://github.com/YunoHost/issues/issues/1484

## Solution

Add all users in the visitors group (Should I create a new migration?)

## PR Status

- Install nextcloud with new permission system:
```
yunohost app install https://github.com/YunoHost-Apps/nextcloud_ynh/tree/new-permissions-system
```
- Add `visitors` permission.
- Try to login
 
## How to test

...

## Validation

- [ ] Principle agreement 0/2 : 
- [x] Quick review 0/1 : Josué
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by Josue-T** [comment]
> (Should I create a new migration?)

Well if we think that we need to fix this also for the actual testing Yes.

**Comment by kay0u** [comment]
Done!

**Comment by alexAubin** [comment]
Zblerg I'm trying to think what's the best option here ...

This fix probably works but I'm afraid that it breaks the semantic and I'd like to avoid having to re-shift all the migrations in unstable to add this new one just because we already released a testing T.T

I'm wondering about another way which would be that : everytime you add `visitors`, it implicitly adds the `all_users` group (if not already there), and forbidding to remove the `all_users` permission if `visitors` is enabled... Which also simplify stuff for app packagers who only have to do `yunohost user permission update --add/remove visitors` to make an app public/private instead of having to remove `all_users`. Still, theoretically that would also require a migration for people already in testing ... or we can make a small script to be ran, that adds `all_users` to all existing perms with `visitors` 

idk :|

**Comment by kay0u** [comment]
Your solution looks better indeed. I'll try to implement it

**Pull request closed without merging**
