### PR TITLE
[fix] Stale / undefined i18n strings

### PR DESCRIPTION
**Pull request by alexAubin**
## The problem

There are many unused i18n strings which creates artificial work for translators ...

Also, some strings which are used in the code are not defined anywhere.

## Solution

I use this small old script in `tests/_test_m18nkeys.py` to parse the code in a very dirty way to identify what strings are used inside `m18n.n` and `YunohostError`

I fixed a few things, but in the these strings are still not defined : 

```
   - apps_already_up_to_date
   - bind_mouting_disable
   - error_reading_file
   - operation_interrupted
   - permission_update_failed_clear
   - permission_update_failed_populate
   - premission_update_failed
```

## PR Status

Should implement / fix those missing strins somehow

## How to test

Uh idk :[ I guess mostly the thing to test is the small refactor about testing the requirements

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by Psycojoker** [comment]
It's great to have done that, it was really a needed job :+1:

**Comment by alexAubin** [comment]
So I rebased the whole PR following https://github.com/YunoHost/yunohost/pull/799 + splitted the small part about requirements checks as asked by Bram, c.f. https://github.com/YunoHost/yunohost/pull/805

**Comment by alexAubin** [comment]
Alright folks, I'm proposing to merge this soon because it's well understood change and in the meantime translators are working on those strings which arent actually used

**Comment by Psycojoker** [comment]
LGTM

**Pull request merged**
