### PR TITLE
[enh] add commands to manage authorized-keys of users

### PR DESCRIPTION
**Pull request by Psycojoker**
Extracted from https://github.com/YunoHost/yunohost/pull/345  to allow smoother merging since this part made consensus.

You need to avoid reading the 2 first commits since they are coming from the previous PR.

### CODE REVIEW

**Comment by Psycojoker** [comment]
This PR is ready to be merged for me (with the https://github.com/YunoHost/yunohost/pull/403 which is included inside of this one) and for reviews.

**Comment by Psycojoker** [comment]
Hello,

Calling for a lighter merge on this one because Aleks is busy on stretch (and I prefer him to be on that part of the code than reviewing this) and that it seems that no one else has time for this PR https://github.com/YunoHost/project-organization/blob/master/yunohost_project_organization_fr.md#validation-all%C3%A9g%C3%A9-en-cas-de-manque-de-relecteurs

**Comment by zamentur** [comment]
Why not make the cli like it:

> yunohost user ssh [allow|disallow|add|list|remove] <USER>

?

**Comment by alexAubin** [comment]
Meh... I kinda agreed with @zamentur ... I don't understand why we should split and introduce a whole new category for this ... These are all for SSH, and are all about users, so having something like `yunohost user ssh [allow|disallow|add-key|list-key|remove-key]` seems logical... 

I mean, the technical part is probably fine, but what we can't change once it's release is the CLI/API design so we really be careful about it :/

**Comment by Psycojoker** [comment]
Apparently none of you remember that this is coming from a whole PR introducing several related function for ssh in its own modules that's I've splitted to merged step by step and that this move to a part of the feature to the user module ... is a changed you've asked in the previous PR -_-

Also this proposed API is ambiguous because it doesn't which kind of keys it talks about, private or authorized keys.

**Pull request merged**
