### PR TITLE
Update nginx SSL conf with new Mozilla recommendation

### PR DESCRIPTION
**Pull request by alexAubin**
## The problem

Nginx ciphers and other security settings not up to date with Mozilla's recommendation (in particular w.r.t. using TLSv1 and 1.1)

## Solution

c.f. https://ssl-config.mozilla.org/#server=nginx&version=1.10.3&config=intermediate&openssl=1.1.1l&ocsp=false&guideline=5.4

Though we can't have any "modern" configuration with 1.10.3... (lack supports for TLS1.3 I believe) Need buster to have nginx 1.14...

## PR Status

Yolocommited, hopefully not breaking everything

## How to test

Regen nginx conf, clear browser cache and test that it works.

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by frju365** [comment]
I may ask the question : What would be the risk in fact to have more recent version of nginx, which doesn't come from debian repos but nginx directly ? Because in fact, nginx repo is normally enough stable, and could be a good thing to have latest features regarding security , DDOS mitigation...

https://nginx.org/en/linux_packages.html#Debian

**Comment by alexAubin** [comment]
I would say there's a risk in terms of creding catastrophic conflicts in some random situations ... We've seen this with sury which ended up removing php7.0-common because php7.3-curl conflicted with it ... (I don't remember exactly) And in the end we should just finish Buster instead of investing energy in "having the new stuff without Buster" ... :/

**Comment by Josue-T** [comment]
Sury also break pip here : https://github.com/YunoHost-Apps/pgadmin_ynh/issues/3

**Comment by alexAubin** [comment]
Ogod ... now that you mention it, i generated these configs with openssl 1.1.1l instead of 1.1.0l

Might be why the core CI is broken with this PR ?

**Comment by alexAubin** [comment]
(In fact, the ssl 1.1.0l requirement doesn't change anything except for Dovecot)

**Pull request merged**
