### PR TITLE
[de] Changed some bad spelling

### PR DESCRIPTION
**Pull request by finster-**
Hope thats okay...

### CODE REVIEW

**Comment by Kloadut** [comment]
I have literally no way to ensure that it is :D

**Comment by finster-** [comment]
Too bad... :) Just leave it open, so maybe some (day) Germans stumble over this pull request and can assure that its okay...

**Comment by Kloadut** [comment]
Incha'allah

**Comment by Kloadut** [comment]
Would you mind taking a look at the `Moulinette`, `Moulinette-yunohost`, `SSOwat` and `YunoHost Admin` projects on Transifex?

https://www.transifex.com/organization/yunohost/

This way we would have a better overview of what have been properly translated/corrected and what have not. :-)

**Comment by jeromelebleu** [comment]
Translations are now done in [Weblate](https://translate.yunohost.org), you're welcome to contribute there! :)

**Pull request closed without merging**
