### PR TITLE
Fix yunomdns

### PR DESCRIPTION
**Pull request by tituspijean**
## The problem

- [x] yunomdns fails if another `yunohost.local` domain is on the network 
- [x] yunomdns service is... silent.

## Solution

- [x] ~~Do not forcibly add `yunohost.local` in the service, the regen-conf takes care of that, Let's let the user remove its line in `/etc/yunohost/mdns.yml`~~
- [x] Use built-in function to append `-2` (and so on) if another service is already on the network
- [x] Introducing my new best friend, `Environment=PYTHONUNBUFFERED=1` 

## PR Status

Ongoing? Waiting for other users feedback.

## How to test

...

### CODE REVIEW

**Comment by alexAubin** [comment]
Eeeeeh I need to think about this and re-read the code, because it's also related to the fact that we want yunohost.local to exists before the postinstall

But maybe we can trick the regenconf to add the proper config snippet in during the regenconf `init`

**Comment by tituspijean** [comment]
Other option, if we detect (how?) another  `yunohost.local`, we increment and publish `yunohost2.local` and so on.

**Comment by tituspijean** [comment]
To be tested. I am a bit surprised by all the `...-2.local` I am getting.

**Comment by tituspijean** [comment]
I'm thinking we could extend the logics implemented in 42729d7 and print a warning whenever a domain is conflicting (and not attempt to publish it, except for yunohost.local).

**Comment by tituspijean** [comment]
Uh, running the diagnostics returns some warnings in triplicates in the log (not the actual diagnosis results):

```
Trouvé 1 objet(s) pouvant être amélioré(s) pour Système de base.
Trouvé 1 objet(s) pouvant être amélioré(s) pour Connectivité Internet.
Could not identify the dns zone for domain deck.local, returning deck.local
Could not identify the dns zone for domain deck.local, returning deck.local
Could not identify the dns zone for domain deck.local, returning deck.local
Could not identify the dns zone for domain elab.local, returning elab.local
Could not identify the dns zone for domain elab.local, returning elab.local
Could not identify the dns zone for domain elab.local, returning elab.local
Could not identify the dns zone for domain n8n.local, returning n8n.local
Could not identify the dns zone for domain n8n.local, returning n8n.local
Could not identify the dns zone for domain n8n.local, returning n8n.local
Could not identify the dns zone for domain node.local, returning node.local
Could not identify the dns zone for domain node.local, returning node.local
Could not identify the dns zone for domain node.local, returning node.local
Could not identify the dns zone for domain outline.local, returning outline.local
Could not identify the dns zone for domain outline.local, returning outline.local
Could not identify the dns zone for domain outline.local, returning outline.local
Could not identify the dns zone for domain test.local, returning test.local
Could not identify the dns zone for domain test.local, returning test.local
Could not identify the dns zone for domain test.local, returning test.local
Could not identify the dns zone for domain wsl.local, returning wsl.local
Could not identify the dns zone for domain wsl.local, returning wsl.local
Could not identify the dns zone for domain wsl.local, returning wsl.local
Tout semble bien pour Enregistrements DNS !
...
```

**Pull request merged**
