### PR TITLE
Enhance the jinja template for bash helpers

### PR DESCRIPTION
**Pull request by Salamandar**
This merge request implement multiple changes in the helper doc template :

* use `</br>` instead of `<space><space>` for line break (spaces at the end of line may be removed by text editors)
* Remove a lot of empty lines created by the Jinja templates (use of `{%- … %}` instead of simple `{% … %}`)

* the biggest change I think : ` {{ h.details.replace('\n', '</br>').replace('_', '\_') }} ` is replaced by ` {{ h.details }} `

My explanation for the latest change : I think the generated markdown should be humanly readable (if not, what's the interest of markdown ?), and those replacements are not needed if the source files are correctly formatted as markdown.

### CODE REVIEW

**Comment by alexAubin** [comment]
Uuuuh have you tested the rendering though (specifically talking about the last change) ? I guess now that we're on Grav the rendering is a bit different so things may indeed change ... but I'm pretty sure we at least need the `.replace('_', '\_')` ... that's because helper names are typically `ynh_foo_bar` but the markdown parser may interpret the `_` as emphasis ...

**Comment by Salamandar** [comment]
> that's because helper names are typically ynh_foo_bar but the markdown parser may interpret the _ as emphasis ...

Yeah, well, why not write it with quotes instead ? (in the shell file i mean)
```
`ynh_foo_bar`
```

The issue with this `replace()` is that we can't use backticks (code blocks) : underscores are replaced in the code blocks too… And that's problematic.

**Comment by Salamandar** [comment]
For the moment, you can't get a correct code block. You can only get one of those : 
* no code block
Capture d’écran du 2021-02-16 14-41-09

* code block with weirdly escaped underscores :
  
Capture d’écran du 2021-02-16 14-41-20

**Comment by alexAubin** [comment]
Ah yes, I guess I'm starting to understand what you mean :sweat_smile: 

Well yup let's go for this then, it just sound a bit fastidious to review/adapt all the helper doc but it's good if somebody is motivated to do it :yum:

**Comment by Salamandar** [comment]
Well I'm already doing it. Not for everything, of course. But little by little everything will be OK.

**Review by alexAubin — APPROVED** [review]

**Review by kay0u — APPROVED** [review]

**Comment by alexAubin** [comment]
(So uuuuuh it's not clear to me, shall we already merge this or are we waiting for some fixes on helpers ?)

**Comment by Salamandar** [comment]
@alexAubin I guess this could be merged, since the doc is "broken" already. I'll work on more fixes progressively.

**Pull request merged**
