### PR TITLE
Reboot function in the admin/tools menu

### PR DESCRIPTION
**Pull request by polytan02**
Reboot function (to be done properly !), to add the possibility of remotely rebooting the yunohost system.  
The function added is JUST AN EXAMPLE and needs to be done properly.

The insterest is to have a dedicated entry in the web interface.

### CODE REVIEW

**Comment by opi** [comment]
Due to #94 from @JocelynDelalande , I guess we must use something else than `os.system` to reboot the server.

But I'd like to have this tool included, especially in InternetCube purpose, as one needs to reboot periodically.

Once this PR is merged, I could implement the admin view ( https://github.com/YunoHost/yunohost-admin/pull/90 )

**Comment by opi** [comment]
@JocelynDelalande is `subprocess.call(['sudo', 'reboot'])` right ?

**Comment by JocelynDelalande** [comment]
> is subprocess.call(['sudo', 'reboot']) right ?

Yes, but you may want to use `subprocess.check_call(['sudo', 'reboot'])` that will raise a `subprocess.CalledProcessError` in case the underlying command do not return a zero-status.

@opi why are you suggesting sudo whereas @polytan02 does not ?

**Comment by opi** [comment]
About `sudo`, it may be a bad habbit from app install script, and maybe not required in moulinette context.
I'll let moulinette-yunohost regular contributors answer.

**Comment by zamentur** [comment]
The actionmap changes are missing.
For the name I suggest simply reboot:

`yunohost tools reboot`

**Comment by Psycojoker** [comment]
If this is for the `yunohost-api` process then it's already running has root and YunoHost forces you to run as root do we don't need a `sudo` here:

```
admin@browny:~$ yunohost app list
Error: yunohost command must be run as root or with sudo.
```

**Comment by Psycojoker** [comment]
I'm interested in seeing this merged and I'm proposing this PR to be a minor decision https://github.com/YunoHost/yunohost-project-organization#d%C3%A9cision-mineure

I'm ready to take on it to finish it.

**Comment by julienmalik** [comment]
Seems a reasonable feature :+1:
Of course, currently it is not mergeable as-is.
OK with @zamentur on the name.

**Comment by opi** [comment]
- should we use `systemctl reboot` ? (don't really know pros/cons)
- should we have a `halt` method too ? I think of internetcu.be boxes that might be turned off properly

**Comment by Psycojoker** [comment]
> should we use systemctl reboot ? (don't really know pros/cons)

I have no idea neither.

> should we have a halt method too ? I think of internetcu.be boxes that might be turned off properly

That could be interesting indeed, dangerous but cool (we need to have a good UX for that to avoid drama). I would do that in another PR however (I love micro PR).

**Comment by mbugeia** [comment]
> should we use systemctl reboot ? (don't really know pros/cons)

That basically the same, check on your yunohost, the reboot command link to systemctl as shutdown and halt.

**Comment by Psycojoker** [comment]
I have reopen this PR here to fix the conflicts https://github.com/YunoHost/yunohost/pull/190

**Comment by Psycojoker** [comment]
Therefor I'm closing this one.

**Pull request closed without merging**
