### PR TITLE
Add mongodb helpers

### PR DESCRIPTION
**Pull request by alexAubin**
Follow-up of https://github.com/YunoHost/yunohost/pull/1838

@orhtej2 was pointing to https://github.com/orhtej2/wekan_ynh/tree/no_keep_version that might be relevant to include in the core

### CODE REVIEW

**Comment by Salamandar** [comment]
Should these helpers only be installed by the mongodb app ?

**Comment by orhtej2** [comment]
I hate mongodb app and wish it died in fire.
On more serious note that requires rewriting packages that rely on MongoDB to, instead of managing MongoDB themselves, rely on extra YNH app. Is that what we want?

**Comment by Salamandar** [comment]
> I hate mongodb app and wish it died in fire.

Why is that ? :D

**Comment by Salamandar** [comment]
Considering those helpers are already used all over the place, i'm OK with merging them into the core.

**Pull request merged**
