### PR TITLE
[enh] Add OpenLDAP TLS support

### PR DESCRIPTION
**Pull request by yalh76**
## The problem

https://github.com/YunoHost/issues/issues/1379

## Solution

Implement TLS Certificate : https://www.openldap.org/doc/admin24/tls.html

## PR Status

...

## How to test

- Apply the patch
- Execute `yunohost tools regen-conf`
- Test using `openssl s_client -connect localhost:636 -showcerts`

Tested with Mastodon LDAP authentication: https://github.com/YunoHost-Apps/mastodon_ynh/pull/165

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by alexAubin** [comment]
(So is this still the right thing to do btw ? I saw a comment about that on yunohost-apps the other day, saying this might be deprecated or something)

**Comment by yalh76** [comment]
> 
> 
> (So is this still the right thing to do btw ? I saw a comment about that on yunohost-apps the other day, saying this might be deprecated or something)

About depreacated stuff, it's me, I made a response to @kayou on matrix when he asked if it wasn't better for mastodon to use simple_tls on port 636 and I responded that ldaps on port 636 is depreacated.

But with thoses changes, certificates are available for ldaps simple_tls 636 and ldap start_tls port 389

**Comment by kay0u** [comment]
> About depreacated stuff, it's me, I made a response to @Kayou on matrix when he asked if it wasn't better for mastodon to use simple_tls on port 636 and I responded that ldaps on port 636 is depreacated.
> But with thoses changes, certificates are available for ldaps simple_tls 636 and ldap start_tls port 389
> So yes, it's still a good thing to do :)

This man knows what he's doing. 😮 (not me >.<)

**Comment by yalh76** [comment]
> 
> 
> > About depreacated stuff, it's me, I made a response to @Kayou on matrix when he asked if it wasn't better for mastodon to use simple_tls on port 636 and I responded that ldaps on port 636 is depreacated.
> > But with thoses changes, certificates are available for ldaps simple_tls 636 and ldap start_tls port 389
> > So yes, it's still a good thing to do :)
> 
> This man knows what he's doing. 😮 (not me >.<)

more or less ^^

**Comment by alexAubin** [comment]
>This man knows what he's doing. :open_mouth: (not me >.<)

Yunohost development be like

noideawhatwedoin

**Comment by Psycojoker** [comment]
> > This man knows what he's doing. open_mouth (not me >.<)
> 
> Yunohost development be like
> 
> noideawhatwedoin

Can confirm :sweat_smile:

**Comment by alexAubin** [comment]
Yolomergin' !

**Pull request merged**
