### PR TITLE
Add script to automatically generate helpers documentation

### PR DESCRIPTION
**Pull request by alexAubin**
## The problem

I created https://github.com/YunoHost/helpersdoc and http://helpers.yunohost.org/ and it was in fact quite stupid to do that on a separated repo + a separate dedicated page just to use Bootstrap 4 cards

## Solution

I reworked the script and CSS to make it compatible with current Simone so that we can integrate it directly in the existing documentation :+1: 

## PR Status

Working

## How to test

Run `python2 generate_helper_doc.py`  and copypasta helpers.html in the doc editor to see how it renders.

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by zamentur** [comment]
To test:
```
sudo apt install virtualenv
virtualenv test
source test/bin/activate
pip install ansi2html
pip install jinja2
python2 generate_helper_doc.py
```

**Comment by alexAubin** [comment]
Ah indeed I might have forgotten about some dependencies /o\

**Comment by zamentur** [comment]
I saw the bug about underscore interpretation

italic

**Comment by zamentur** [comment]
ynhaddsystemdconfig too

**Comment by alexAubin** [comment]
Hmmm, can you still reproduce it after clearing the cache of the doc + making sure that you have `<!-- NO_MARKDOWN_PARSING -->` on top ?

**Comment by alexAubin** [comment]
(Checked with @zamentur and this is fixed)

**Comment by zamentur** [comment]
It was a cache issues , so it works completely

**Pull request merged**
