### PR TITLE
Mysql mariadb get status

### PR DESCRIPTION
**Pull request by Psycojoker**
## The problem

Fixes https://github.com/YunoHost/issues/issues/1134

## Solution

Offers a list of alternates names, doesn't fail on failed to grab a service.

## PR Status

Tested and working.

## How to test

Do a regen-conf.

Have a situations where you have mariadb instead of mysql or hack `/etc/yunohost/services.yml` to replace "mysql" by "mariadb" then put "mysql" as an alternates on "mariadb" and do a `yunohost service status mariadb`.

## Validation

Since it's a fix to an already accepted PR I'm really tempted to put that as a microdecision. Let's way a bit in case of.

### CODE REVIEW

**Comment by alexAubin** [comment]
Apparently somebody has a similar issue with postfix : https://forum.yunohost.org/t/beta-testing-phase-for-yunohost-3-0-on-debian-stretch/4798/106

```
   Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 406, in process
        ret = self.actionsmap.process(arguments, timeout=30, route=_route)
      File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 498, in process
        return func(**arguments)
      File "/usr/lib/moulinette/yunohost/service.py", line 228, in service_status
        status = _get_service_information_from_systemd(name)
      File "/usr/lib/moulinette/yunohost/service.py", line 265, in _get_service_information_from_systemd
        service_path = manager.GetUnit(service + ".service")
      File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
        return self._proxy_method(*args, **keywords)
      File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
        **keywords)
      File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
        message, timeout)
    DBusException: org.freedesktop.systemd1.NoSuchUnit: Unit postfix.service not loaded.
```

But checking status with systemctl works ?

```
postfix.service - Postfix Mail Transport Agent
   Loaded: loaded (/lib/systemd/system/postfix.service; enabled; vendor preset: 
   Active: active (exited) since Tue 2018-05-29 21:00:51 UTC; 53min ago
  Process: 1029 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 1029 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/postfix.service

May 29 21:00:51 domain.nohost.me systemd[1]: Starting Postfix Mail Transport Agent
May 29 21:00:51 domain.nohost.me systemd[1]: Started Postfix Mail Transport Agent.
```

Not sure I understand why :/

**Comment by Psycojoker** [comment]
Okay, I really don't understand why for postfix here :|

That's really super weird :/

**Comment by Psycojoker** [comment]
Let's merge it and get back to this postfix person once you've made a new release maybe?

**Comment by alexAubin** [comment]
Yep, that might be a different issue than this thing with mysql

**Comment by Psycojoker** [comment]
Ok, merging then.

**Pull request merged**
