### PR TITLE
add ssh port setting

### PR DESCRIPTION
**Pull request by kay0u**
## The problem

...

## Solution

Close https://github.com/YunoHost/issues/issues/1740

We probably want a migration to handle the current port, IDK if we need to do something for https://github.com/YunoHost/yunohost/blob/ce64a6380abfe0c8b9892172fd72c901c2685d36/data/templates/yunohost/services.yml#L46

## PR Status

...

## How to test

...

### CODE REVIEW

**Comment by kay0u** [comment]
I've found this dirty hack too:
https://github.com/YunoHost/yunohost/blob/ce64a6380abfe0c8b9892172fd72c901c2685d36/src/yunohost/service.py#L683-L688

**Comment by alexAubin** [comment]
Sounds okay because as you saw, during the diagnosis / service stuff we fetch the port directly in the file so that covers the case where it got manually modified (and/or defined through settings)

**Comment by zamentur** [comment]
What about fail2ban, i remember some port should be change in Fail2ban.

**Comment by kay0u** [comment]
I don't fully understand this conf file, but there is no 22 port in this file
https://github.com/YunoHost/yunohost/blob/fc818cc6a7ec9281adc24a3b98fd6c0a6e761a8a/data/templates/fail2ban/jail.conf#L224-L250

**Comment by zamentur** [comment]
yep but ssh mean "default ssh port" so 22...

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/yunohost/commit/37c0825eed421acadd0a7528dbab8172695eed8f

**Pull request merged**
