### PR TITLE
Upgrade n to v7.0.0

### PR DESCRIPTION
**Pull request by ericgaspar**
## The problem

...

## Solution
Upgrade to new version upstream 7.0.0
...

## PR Status

...

## How to test

...

### CODE REVIEW

**Review by yalh76 — APPROVED** [review]
I don't know if would be better to wait for a minor version like 7.0.3 or 7.1.1 or whatever

**Comment by ericgaspar** [comment]
This is not a major release version as the number suggests

**Comment by yalh76** [comment]
> 
> 
> This is not a major release version as the number suggests

Ready to merge then ^^

**Comment by alexAubin** [comment]
Cheers !

**Pull request merged**
