### PR TITLE
Allow dots in usernames

### PR DESCRIPTION
**Pull request by alexAubin**
cf https://github.com/YunoHost/issues/issues/2287

### CODE REVIEW

**Review by Tagadda — APPROVED** [review]

**Comment by zamentur** [comment]
What about the consequences for apps doesn't supporting dot in their internal database ? In general, apps (with ldap integration) maps LDAP uid with the username field.

**Comment by alexAubin** [comment]
Do we know of such apps that would not allow for dots in username ? x_x

**Comment by zamentur** [comment]
> Do we know of such apps that would not allow for dots in username ? x_x
I don't

I succeed to create a user with dot in nextcloud UI but from cli i have "User ID used to login (must only contain a-z, A-Z, 0-9, -, _ and @)" :/

I succeed too on limesurvey.

Anyway, i think on 500 apps, we probably having several apps which doesn't support it... However, all apps doesn't support SSO or LDAP or BASIC AUTH...

**Comment by alexAubin** [comment]
So nextcloud does allow to create user with a dot from its webui (and it works?), but not from the cli ? x_X

**Comment by zamentur** [comment]
> So nextcloud does allow to create user with a dot from its webui (and it works?), but not from the cli ? x_X
i didn't really try on cli, just read the `occ user:create --help` doc...

**Comment by Tagadda** [comment]
At $dayjob we have OwnCloud working with LDAP and users with dots in the username :D

**Pull request merged**
