### PR TITLE
SSL negociation better

### PR DESCRIPTION
**Pull request by liberodark**
For low cpu use recommended by nginx

## The problem

...

## Solution

...

## PR Status

...

## How to test

...

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by zamentur** [comment]
I have no point of view on this change. 

Could you give some references or reasons explaining why it should be better ?

**Comment by alexAubin** [comment]
I too would like to see some references about this ... this looks quite arbitrary just like this.

**Comment by liberodark** [comment]
I will give information: D
I did not have much time yet sorry!

**Comment by alexAubin** [comment]
Bump :/

**Comment by frju365** [comment]
Still don't understand why this PR is set as "work needed" ? (it's much more opinion needed as we are in discussion and nothing will be added to the PR as far as the goal is already done)

@liberodark : Did you have time to search for documentation ?

**Comment by frju365** [comment]
yes, I agree totally ;) It was not a reproach. I wanted just to know why "work needed". But yes, we need a more info, sure (it's what I said).

**Comment by alexAubin** [comment]
Closing due to lack of feedback ... feel free to reopen if there are detailed motivation behind this change.

**Pull request closed without merging**
