### PR TITLE
Add a sleep 2 before systemctl

### PR DESCRIPTION
**Pull request by yalh76**
## The problem
https://github.com/YunoHost/issues/issues/1573

## Solution
Add a sleep 2 before systemctl 

## PR Status
Ready and tested

## How to test
Do recurring backup of an app

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by alexAubin** [comment]
Hmmmmm shall we increase it to something like 5 to cover slower hardware ?

**Comment by maniackcrudelis** [comment]
Huh, we have a lot of ynh_systemd_action in app scripts and helpers. A sleep 5 will soon become a sleep 20 or 30

**Comment by alexAubin** [comment]
Ah yeah, didn't think about that, nevermind xD

**Comment by maniackcrudelis** [comment]
Also, it's really a very specific problem that we didn't really spot...
ynh_systemd_action start to follow the log before doing any action, but somehow, sometime it missed the first line !

**Comment by yalh76** [comment]
Maybe for now a `sleep 2` could be a good start ?

**Comment by alexAubin** [comment]
Do you folks want this as a hotfix for 3.7.x as well ?

**Comment by maniackcrudelis** [comment]
Really not a hot fix.
And actually wondering if really worth it at all

**Pull request closed without merging**
