### PR TITLE
[fix] Nodejs helpers : use YNH_APP_INSTANCE_NAME instead of YNH_APP_ID

### PR DESCRIPTION
**Pull request by yalh76**
## The problem

f you install two time the same application, when removing one of them, nodejs is uninstalled

## Solution

YNH_APP_INSTANCE_NAME instead of YNH_APP_ID

## PR Status

...

## How to test

...

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by alexAubin** [comment]
LGTM, Would be nice to merge this for 3.5.

Any confirmation from @YunoHost/apps that this is alright ?

**Comment by kay0u** [comment]
I'm wondering, what about apps already using this help? :worried:

**Comment by alexAubin** [comment]
Then I guess the line won't properly get removed and nodejs won't be uninstalled ... But in the nominal case it should be fine as the app id is usually the instance name .. only in multiinstance install you have foo instance "foo" vs. "foo__2"

So for existing install with multi-instance app, there's a small issue yes, but I think we can live with it ..?

**Comment by kay0u** [comment]
Ok

**Comment by yalh76** [comment]
> I'm wondering, what about apps already using this help?

At least:

- distbin
- mastodon
- peertube
- wekan
- wikijs

**Pull request merged**
