### PR TITLE
[fix] Wrong fail2ban regex for yunohost

### PR DESCRIPTION
**Pull request by zimo2001**
In my nginx_error.log, the authentication errors are "helpers.lua", not "access.lua".

### CODE REVIEW

**Comment by Psycojoker** [comment]
I confirm that I have the same logs that you.

I'm changing the target branch from stable to unsable has this is our workflow.

Thanks your contribution :heart:

**Comment by zimo2001** [comment]
Thanks for approving!

**Comment by Psycojoker** [comment]
I've changed to the branch in which to merge, this is probably the reason of those new commits, I can do the merge by hand.

**Comment by Psycojoker** [comment]
Hello,

I've merged this PR by cherry-picking this commit https://github.com/YunoHost/yunohost/pull/215/commits/f6956207605b4fc2f10bab7797aeac754e48ca60

Thanks again :)

**Comment by Psycojoker** [comment]
Aaaand, I'm an idiot. I've fixed that.

**Pull request merged**
