### PR TITLE
Create .gitlab-ci.yml

### PR DESCRIPTION
**Pull request by kay0u**
## The problem

No CI

## Solution

I propose to add this file to use the gitlab-ci.

This file will run the `postinstall` of yunohost on a gitlab runner, and all the tests we wrote on https://github.com/YunoHost/yunohost/tree/stretch-unstable/tests and https://github.com/YunoHost/yunohost/tree/stretch-unstable/src/yunohost/tests.

You can see it in action [here](https://gitlab.com/kay0u/yunohost/pipelines/98358737) or [here](https://gitlab.com/yunohost/yunohost/pipelines/98951276)

To work, it needs a specific runner, available [here](https://framagit.org/kay0u/yunohost-ci) mirrored on github [here](https://github.com/kay0u/yunohost-ci). Feel free to contribute on framagit, or if you want I can transfer this project on YunoHost organisation. If you have any question on how to configure the runner on a gitlab instance contact me, I'll be happy to help you. For your information I tested it on a Virtualbox running a debian stretch.

To implement this solution, there are many solutions:
- Do not use gitlab-ci and work on an external solution as we do for CI_package_check.
- Migrate right now on framagit.org, and mirror our repo on github. (With this solution we can have all benefits of Gitlab CI, but the migration cost is a big thing).
- Mirror manually (webhook could do it?) our github projects to framagit.org. (With this solution we don't have automatic CI on PR)
- Use gitlab.com which provides for free a mirror from github.com to gitlab.com, but it's free until [March 22nd, 2020](https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html#pulling-from-a-remote-repository-starter). (With this solution we have automatic CI on PR, but we have it for free for a limited period).

I'm opening the discussion.

## PR Status

...

## How to test

...

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by frju365** [comment]
Well It's very good to use gitlab-ci, but, I don't know if we agree with migrating to framagit after framasoft told users that they will close registration to most of their services in 1-2 years. Perhaps I'm wrong and it has been discussed (I was not here since 3-4 meetings, so I don't know).

For me ideal would be to mirror manually to framagit and perhaps other hosts and do test on framagit.

However, I don't understand why we couldn't have automatic CI test on PR with this solution ?

**Comment by kay0u** [comment]
> Well It's very good to use gitlab-ci, but, I don't know if we agree with migrating to framagit after framasoft told users that they will close registration to most of their services in 1-2 years. Perhaps I'm wrong and it has been discussed (I was not here since 3-4 meetings, so I don't know).

I didn't know that framagit was concerned about that. In that case we must discuss on which instance we want to move.

> However, I don't understand why we couldn't have automatic CI test on PR with this solution ?

To have a proper solution, well integrated to GitHub, which trigger automatically tests and displayed on the PR like [this](https://github.com/kay0u/yunohost/pull/2) for example (look CI in the PR), we need the paid version of gitlab mirror (free until march), I don't know exactly how to test PR from a fork with the solution base on a manual mirror.

**Comment by frju365** [comment]
ok. Isn't this feature enable in community edition (dev edition) of gitlab ? Because perhaps other instance than gitlab.org have it (couldn't we do the same system with gitlab api ?). 

However, if we move to framagit or another, we won't need it.

**Comment by yalh76** [comment]
Maybe another option would be to have  our own gitlab + gitlab-runner. In that case we would not framasoft mirroring limitation.

For example, yunohost repo stays at github. 
Our own gitlab can have a mirror of that repo and able to run runners automatically....

**Comment by kay0u** [comment]
It's indeed a solution, the fact is that Gitlab needs a lot of resources, if we have a good server to host it, we can consider it.

**Comment by kay0u** [comment]
We can get a free ultimate license:

https://about.gitlab.com/solutions/open-source/program/#gitlab-oss-form

**Comment by kay0u** [comment]
Erratum: https://about.gitlab.com/releases/2020/03/12/free-period-for-cicd-external-repositories/

> So, what exactly does this mean for you?
>- The ability to mirror private external repositories and run CI/CD on them will no longer be available as of March 22, 2020, unless the repositories have been made public or you have upgraded to an eligible GitLab plan.
[...]

This is ending only for private repo

**Comment by kay0u** [comment]
#897

**Pull request closed without merging**
