### PR TITLE
[enh] New helpers for logrotate

### PR DESCRIPTION
**Pull request by maniackcrudelis**
Add and remove logrotate config

### CODE REVIEW

**Comment by zamentur** [comment]
What about legal obligation, I think in France we should delete logs after 366 days.

**Comment by alexAubin** [comment]
Imho this is beyond the scope of this PR. At the moment I don't think nginx logs (and others) olders than 1 year are deleted... But that's probably something we should address.

**Comment by Psycojoker** [comment]
Up

**Comment by alexAubin** [comment]
I haven't tested it, but if you guys (@maniackcrudelis and @Psycojoker) did, then let's merge it

**Comment by JimboJoe** [comment]
@maniackcrudelis could you please point us to an application using that helpers?

**Comment by maniackcrudelis** [comment]
Minidlna use it, but the repository is not up to date.
But, we'll don't merge this helper for the moment. We have a small error with the optional argument, that trig the previous set -u

**Comment by maniackcrudelis** [comment]
Tested, it's ok.

**Comment by alexAubin** [comment]
This PR looks mergeable to me. (Not tested / reviewed but I trust you guys 😉 )

**Pull request merged**
