### PR TITLE
[enh] Set Path as full-path

### PR DESCRIPTION
**Pull request by frju365**
## The problem

- Problem during test because of this. I got /etc/nginx/conf.d/conf.d/...

## Solution

- Set a real path

## PR Status

Tested. Micro-decision.

## Future

- Perhaps add gixy tool in core

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by alexAubin** [comment]
Uh but how did you end up with this `/etc/nginx/conf.d/conf.d/` thing ? o.O"

**Comment by Josue-T** [comment]
I thought about using gixy in the CI. I think it could be really a good improvement about security.

**Comment by frju365** [comment]
Yes. Indeed.

**Comment by frju365** [comment]
done.

**Comment by alexAubin** [comment]
Yolomergin' ¯\\\_(ツ)\_/¯

**Pull request merged**
