### PR TITLE
 [add] ynh_url_join

### PR DESCRIPTION
**Pull request by kay0u**
## The problem

...

## Solution

Add a helper that can join several url together

## PR Status

Tested

## How to test

`ynh_url_join example admin index.php`
`ynh_url_join /example admin /index.php`
`ynh_url_join /`

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
What's the purpose of this helper @kay0u ?

**Comment by kay0u** [comment]
I needed it in an app, so I make a proposal...

**Comment by maniackcrudelis** [comment]
Yep, so far I was guessing that.
My question was more what the use case of this helper?
Can't see any usage of it

**Comment by kay0u** [comment]
For me, here:

https://github.com/YunoHost-Apps/dotclear2_ynh/blob/testing/scripts/install#L108

and:

https://github.com/YunoHost-Apps/dotclear2_ynh/blob/testing/scripts/install#L127

**Comment by maniackcrudelis** [comment]
But! Why not simply concatenate the path together!?
If it's only because of a double path, remove it. It's would be easier

**Comment by kay0u** [comment]
That's exactly what i've done before, but i was not happy with an `if path_url == "/"`

But, if you think it's not a helper really helpfull, you can close this PR without any problem :-)

**Comment by maniackcrudelis** [comment]
For me it looks like an edge case. Never heard before of an app for which it was really a problem.
Meanwhile, you can add this helper to the [experimental repo](https://github.com/YunoHost-Apps/Experimental_helpers) and use it in dotclear.
While in experimental helpers repo, maybe it will meet its public.

Maybe other from @YunoHost/apps group would have a different opinion ?

**Comment by JimboJoe** [comment]
Well I agree with @maniackcrudelis that you could submit it to experimental helpers first. Although it's ugly, double slashes have usually no impact... :man_shrugging:

**Pull request closed without merging**
