### PR TITLE
Update nginx ciphers (requires Buster)

### PR DESCRIPTION
**Pull request by liberodark**
## The problem

The see new recomendation of mozilla

## Solution

This config work on stretch for intermediate and buster for modern.
https://ssl-config.mozilla.org/

Modern config work with : 
- Supports Firefox 63, Android 10.0, Chrome 70, Edge 75, Java 11, OpenSSL 1.1.1, Opera 57, and Safari 12.1

Intermediate config work with : 
-  Supports Firefox 27, Android 4.4.2, Chrome 31, Edge, IE 11 on Windows 7, Java 8u31, OpenSSL 1.0.1, Opera 20, and Safari 9 

## PR Status

Wait for reply

## How to test

Just need to apply this on server test

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by frju365** [comment]
Ok. This doesn't work on Stretch. 
This update follows new version of Debian which includes newer version of nginx. We will have to wait for new version of Yunohost to apply this configuration For the form, everything is ok from my point of view.

@alexAubin : Is there a way to flag this as "Buster" PR ?

**Comment by liberodark** [comment]
Better now for the name ?

**Comment by frju365** [comment]
yes, fine. I just ask to @alexAubin, because I remember we had such organization for Stretch ;-) Thanks !

**Comment by alexAubin** [comment]
Done in https://github.com/YunoHost/yunohost/commit/f3a4334a13aec8e73af7e00f85400eab1db9b3a5 because that was easier than fixing the whole bunch of conclicts since 1 year ago

**Pull request closed without merging**
