### PR TITLE
Add min version for all helpers

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## The problem

When packaging, it can be difficult to evaluate the minimal version of YunoHost you should require.

## Solution

Add the minimal version required for each helpers.
Unfortunately, it will be hard to maintain...

## PR Status

Ready for reviews

## How to test

...

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by Josue-T** [comment]
It will quite difficult but I think that it's also important to know the change. By example for the nginx helper, we added the argument to pass some other variable to change. I think that this information is as important as the version when the helper was interoduced. For getops too.

Maybe we can write the required version since the last change...

**Comment by alexAubin** [comment]
>Maybe we can write the required version since the last change...

Sooo do we implement this or merge as is ? Personally I'd say if those non-backward compatible changes are from before 3.0 we can ignore it :/

**Comment by maniackcrudelis** [comment]
It's more changes after the version 3.
But I think it's already going to be hard to maintain those version numbers...

**Comment by alexAubin** [comment]
Sooo uuuh, to merge or not to merge, that is the wondering ̣¿:o|

**Comment by maniackcrudelis** [comment]
Let's merge in 3 days ;)

**Pull request merged**
