### PR TITLE
[fix] ynh_psql_remove_db fail

### PR DESCRIPTION
**Pull request by zamentur**
## The problem

The psql remove database helper fail with several message

## Solution

Remove small error in db exist test

## PR Status

Ready

## How to test

...

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by zamentur** [comment]
Note : I mark this important cause it make fail remove, reinstallation, and some restoration of all postgresql app

**Comment by alexAubin** [comment]
Not sure to understand the implication, but shall we release this as a hotfix for 3.5 ?

**Comment by zamentur** [comment]
> Not sure to understand the implication, but shall we release this as a hotfix for 3.5 ?

Could be good. Otherwise psql apps are like level 2

https://github.com/search?q=org%3AYunoHost-Apps+psql&type=Code

Note: a lot of apps embed their own psql helpers (and will work)

**Comment by alexAubin** [comment]
Hotfix being released in 3.5.2.2

**Pull request merged**
