### PR TITLE
Fix sury v99999

### PR DESCRIPTION
**Pull request by kay0u**
## The problem

Sury, again (the current solution seems to work, but it's not really conventional)

## Solution

Apply Pin recommended by @taziden 
I don't know if it's better this way, tell me

## PR Status

Tested with:
- Install nextcloud
- Install Weblate ([buster](https://github.com/YunoHost-Apps/weblate_ynh/tree/buster) branch)
- Install Snipeit ([fix-buster](https://github.com/YunoHost-Apps/snipeit_ynh/tree/fix-buster) branch)
- Install Synapse

No problems so far

## How to test

...

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by Josue-T** [comment]
Look like good.

Maybe the question would if we install synapse which need the libxml and if we also install an other php app which need php7.4-xml.

**Comment by kay0u** [comment]
I guess it's related to this [issue](https://github.com/YunoHost-Apps/synapse_ynh/issues/193)
let's play with php7.4-xml:
```
root@domain:/ynh-dev# apt install php7.4-xml
php7.4-xml is already the newest version (7.4.6-1+0~20200514.17+debian9~1.gbp0f509e).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

root@domain:/ynh-dev# apt-cache policy libxml2-dev
libxml2-dev:
  Installed: 2.9.9+dfsg-1+0~20200226.5+debian9~1.gbp3b6674
  Candidate: 2.9.9+dfsg-1+0~20200226.5+debian9~1.gbp3b6674
  Version table:
 *** 2.9.9+dfsg-1+0~20200226.5+debian9~1.gbp3b6674 995
        995 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     2.9.4+dfsg1-2.2+deb9u2 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Packages

root@domain:/ynh-dev# yunohost app install synapse 
```
and the logs of the install: (spoiler, everything is installed)
https://paste.yunohost.org/raw/viguzesahe

**Comment by Josue-T** [comment]
Thanks for the feedback

**Comment by kay0u** [comment]
the question is what to do with servers already screwed up by Sury?

**Comment by alexAubin** [comment]
Doesn't this change already take care of the smooth migration of existing sury repo ? (Well, they'll have to run an app script that tries to install php stuff for it to actually be applied ... but it sounds precisely like the situation we're trying to fix ... though granted that it would be cleaner to have a "real" migration so that there's no sudden weird conf change just by attempting to install an app but I don't know if that's worth the effort of implementing a migration...)

**Comment by alexAubin** [comment]
Alright folks I'm yolomerging because somebody again had an issue with sury today and I'm tired of that shit é_è

**Pull request merged**
