### PR TITLE
[enh] Dovecot extensible configuration

### PR DESCRIPTION
**Pull request by julienmalik**
This set of commits allow anyone (apps typically) to extend dovecot configuration.
The intendend use is to enable specific plugins not included in the base yunohost conf.

One use case experiment is : https://github.com/YunoHost-Apps/ftssolr_ynh to enable Solr based Full Text Search. (which I currently run successfully in production on my ynh box)

### CODE REVIEW

**Comment by julienmalik** [comment]
Calling for a small decision

**Comment by Psycojoker** [comment]
I have no knowledge of dovecot so I'm to trust the opinion of the others here.

**Comment by julienmalik** [comment]
If you want to test you can :

```
$ doveconf -n
```

This prints the current config interpreted by dovecot from the config files.

The idea is that this PR does not change anything about the config, except for the autosubscribe & autosubscribe2 that I cleaned up during this refactoring.

For the rest, I admit the dovecot configuration language is a pain in [...].

**Comment by julienmalik** [comment]
ping : any opinion ?

**Comment by Psycojoker** [comment]
No, I suck at email and haven't taken the time to follow your instructions :/

**Comment by opi** [comment]
I have exported dovecot configuration before and after using your PR (with a `service regen-conf dovecot` between), and this diff is self-speaking : 

```
diff dovecot_unstable.conf dovecot_pr_175.conf 
4d3
< login_greeting = Dovecot ready!!
26,27d24
<   autosubscribe = Trash
<   autosubscribe2 = Junk
```

also here is the `regen-conf` output : 

```
root@yunohost:~# yunohost service regen-conf dovecot
Success! The configuration has been updated for service 'dovecot'
dovecot: 
  applied: 
    /etc/dovecot/dovecot.conf: 
      status: updated
    /etc/dovecot/yunohost.d/post-ext.conf: 
      status: created
    /etc/dovecot/yunohost.d/pre-ext.conf: 
      status: created
  pending: 
```

great job @julienmalik

**Comment by alexAubin** [comment]
I have no knowledge about dovecot, but I'll try to test before the end of the week, see if I get the same result as observed by opi.

**Comment by Psycojoker** [comment]
We need another opinion on this one.

**Pull request merged**
