### PR TITLE
[fix] handle the case where services[service] is set to null in the s…

### PR DESCRIPTION
**Pull request by ZeHiro**
…ervices.yml. Fix #785

### CODE REVIEW

**Comment by ZeHiro** [comment]
The fix will work in this specific case of the detected error, but perhapse it should be better to sanitize the null/None values in a proper helper. load_and_sanitize_yaml (path_to_yaml) : return sanitized Dict

**Comment by alexAubin** [comment]
Don't know much about conf-regen, but I had to tweak also get_conf_hashes to fix the Traceback stuff when trying to reproduce.

Thanks for the PR btw !

**Comment by ZeHiro** [comment]
You're welcome, it was an easy fix :-)

**Comment by alexAubin** [comment]
Bump ! Would be nice to have another feedback, this is relatively easy / small to review.

I tested it by editing services.yml, replacing the whole ssl block by just `ssl : null`, then running `yunohost service regen-conf --force` if I remember correctly.

**Pull request merged**
