### PR TITLE
[fix] typo fix.

### PR DESCRIPTION
**Pull request by M5oul**

### CODE REVIEW

**Comment by jeromelebleu** [comment]
It's *a URL* and not *an URL*, see: http://itknowledgeexchange.techtarget.com/writing-for-business/which-is-correct-a-url-or-an-url/.

**Comment by M5oul** [comment]
Wow, thanks. Didn't know about it.

**Comment by M5oul** [comment]
Ok, let's close this PR. `your` word is not so problematic.

**Comment by jeromelebleu** [comment]
Ok! Note that I didn't known too, it's thanks to this contribution https://github.com/YunoHost/yunohost/pull/153!

**Pull request closed without merging**
