### PR TITLE
[fix] Rmilter's DKIM settings first, as they can't be overridden

### PR DESCRIPTION
**Pull request by opi**

### CODE REVIEW

**Comment by opi** [comment]
Note that using rmilter for dkim signing is deprecated. We should implement up-to-date behavior soon https://github.com/vstakhov/rmilter/issues/174

**Comment by opi** [comment]
test process: watch `/var/log/mail.log` while sending mail

If you see any error like "cannot find key for domain xxx", it means your DKIM configuration is bad. (Note that you should always see "added DKIM signature")

**Comment by polytan02** [comment]
I have tested this on : 
- [x] YnH upgraded from 2.4 to 2.5
- [x] new x86-64 vm
- [x] new arm vm

and in every cases it solved the issue.

**Comment by alexAubin** [comment]
Hi there,

I tested it in 2.5.5 but I can't reproduce the issue : rmilter correctly signs outgoing mail with and without this PR (applied manually). I'm on a digital ocean droplet, and rmilter version is 1.8.6. So all I can say is that there's no regression :/.

Any hint about how to reproduce the initial issue ?

**Comment by polytan02** [comment]
@alexAubin if you go there https://www.mail-tester.com/ and send an email, you get 10/10 ?

**Comment by opi** [comment]
>  rmilter version is 1.8.6

@alexAubin on stable branch of yunohost you should have rmilter 1.9.2 ; Are you up to date ?

**Comment by alexAubin** [comment]
After dist-upgrade, I now have rmilter 1.9.2 but still cannot reproduce...

**Comment by alexAubin** [comment]
Btw to me, it's still not clear what was the exact problematic situation this PR is supposed to fix. As reported here : https://forum.yunohost.org/t/rmilter-1-9-2-no-more-dkim-signature/2487 , and (by Maxime, I guess ?), at some point DKIM signing stopped working, which I am still not able to reproduce :/. On the other hand, they seem to report that this PR fixes the situation so I guess it's okay...

**Comment by opi** [comment]
*sorry for french, tired & lazy*

(22:22:19) opi: donc, bilan en francais (parce que flemme de rediger en anglais sur github) pour https://github.com/YunoHost/yunohost/pull/256.  J'ai complété ma PR en ajoutant un fichier de config dedié a DKIM (/etc/rmilter.conf.d/ynh_dkim.conf) qui est ce-que-devrait-etre la config si tout allait bien

(22:22:53) opi: j'ai néanmoins laissé (en dupliqué donc) la conf DKIM dans le /etc/rmilter.conf , pour etre sur que ca marche

(22:23:22) opi: j'ai également fixé un permission sur /etc/dkim, on sait jamais https://github.com/YunoHost/yunohost/pull/256/files#diff-2b0eee7343ff4ae404e5fd2c05ae757fR32 (j'ai vu ça dans les issues de rmilter)

**Comment by Psycojoker** [comment]
This has been squash and merged by hand by opi in stable and retro merged in other branches.

**Comment by opi** [comment]
squashed here 1c2de37f6338cdd35f04adecc2b6a4bc0d9b4f87

**Pull request closed without merging**
