### PR TITLE
[fix] don't remove trailing char if it's not a slash

### PR DESCRIPTION
**Pull request by Psycojoker**
Attempt to fix https://dev.yunohost.org/issues/655

ping @maniackcrudelis could you test and confirm that this works for you plz?

I've done a minimal solution, this part of the code should be cleaned a bit more.

### CODE REVIEW

**Comment by Psycojoker** [comment]
```
19:20  <ManiackC> @Bram à première vue ça marche niquel ton fix
19:20  <ManiackC> Sans le slash, ce n'est pas tronqué et avec il n'est pas en double
```

**Comment by Psycojoker** [comment]
Looking again at it I think that `os.path.join` would be better but I still want to do the most minimalist patch possible to avoid breaking other things.

**Comment by Psycojoker** [comment]
Ah didn't know you could give [rl]strip an argument, that looks indeed better.

**Comment by likeitneverwentaway** [comment]
I had the problem with every installed app, this correctly fixes the ssoconf.

**Comment by Psycojoker** [comment]
@alexAubin should be ok

@maniackcrudelis can you test again plz?

**Comment by maniackcrudelis** [comment]
Tested, no regression on "ssowat/conf.json" with rstrip.

**Comment by Psycojoker** [comment]
Thx <3

**Pull request merged**
