### PR TITLE
[enh] Add unit/functional tests for apps

### PR DESCRIPTION
**Pull request by alexAubin**
## The problem

We don't have tests for apps '-'

## Solution

Implement some ...

## PR Status

Tested on my machine, but still need to implement at least 3 of them

I think I spotted an important issue related to LDAP group permissions related to failed remove, gotta investigate

## How to test

Run the tests using ynh-dev or pytest manually

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by Josue-T** [comment]
> I think I spotted an important issue related to LDAP group permissions related to failed remove, gotta investigate

Do you have any log. Maybe I could help to investigate...

**Comment by alexAubin** [comment]
> Do you have any log. Maybe I could help to investigate...

It's not clear to me how to reproduce ... but basically some times I ended up with the check_ldap_db_consistency failing because some remaining permission existed for an app that was supposed  to be uninstalled ... That might be because I was tweaking a lot of code and the remove operation was sometime failing because before the part where it removes the thing from ldap.

So maybe I'll just wrap stuff in try/except to avoid that kind of things in the future even though that seems to happen mainly during dev.

>Documentation addition to the README on how to run these?
>They need to be run in the context of ynh-dev / live yunohost or?

Yes, in the context of a post-installed yunohost. I use `./ynh-dev test yunohost/apps` to run them, (c.f. [here](https://github.com/YunoHost/ynh-dev/blob/master/ynh-dev#L301-L340)) or you can run pytest by hand

**Comment by alexAubin** [comment]
Proposing to merge soonish though I will implement the last tests for https://github.com/YunoHost/yunohost/pull/769

**Comment by alexAubin** [comment]
So that was painful ... but I finally implemented and ran the remaining tests which allowed to find bugs in  https://github.com/YunoHost/yunohost/pull/769 and https://github.com/YunoHost/yunohost/pull/785 so we're good to go

The whole triptic of PR is a mess : this one is based on https://github.com/YunoHost/yunohost/pull/785 itself based on https://github.com/YunoHost/yunohost/pull/769  so i temporarily changed the base branch to this one is based on https://github.com/YunoHost/yunohost/pull/785 in case you want to read the relevant commit of this PR easily...

**Pull request merged**
