### PR TITLE
[fix] Rspamd & Rmilter are no more sockets

### PR DESCRIPTION
**Pull request by opi**
Changes introduced by https://github.com/YunoHost/yunohost/commit/b419c8c5641f29284befc29b059ee37db0b74a59

### CODE REVIEW

**Comment by opi** [comment]
See https://github.com/YunoHost/yunohost/pull/226 too

**Comment by Psycojoker** [comment]
Has this been tested? If so, I think we can merge it right await.

**Comment by opi** [comment]
I tested it on production.

anyone can manually change his compiled `/etc/yunohost/services.yml` and try `yunohost sercice status` to see the changes to rmilter/rspamd status.

**Comment by polytan02** [comment]
I also have this issue on my fresh ynh install and changing into .service then yunohost tools regen-conf hasn't solved the issue. I still have a connection refused on rmilter.

**Comment by alexAubin** [comment]
There are still some residual use of .socket : https://github.com/YunoHost/yunohost/search?q=rmilter.sock&type=Code&utf8=%E2%9C%93

As reported, it actually breaks mail sending on new instances :/

**Comment by alexAubin** [comment]
Investigated a bit with [this doc](https://rspamd.com/doc/quickstart.html) and [this doc](https://rspamd.com/doc/integration.html#configuring-postfix). We might want to have something like : 

```
In rmilter.conf
------------------
bind_socket = inet:9900@127.0.0.1;


In postfix/main.cf
-----------------------
smtpd_milters = inet:localhost:9900
```

Not fully tested though.

**Comment by julienmalik** [comment]
@alexAubin "sytemd socket" is actually not related with the notion of "unix sockets" : the rmilter/rspamd systemd service can start a unix socket, and we connect other apps to this unix socket.

systemd socket means : start something that listen on a port or a socket, but don't start the underlying process immediately. start the underlying process only the first time the socket is used.

**Comment by zamentur** [comment]
Maybe there is no postfix chroot in /var/spool/postfix/ on some setup ?

https://github.com/YunoHost/yunohost/blob/unstable/data/templates/rmilter/rmilter.conf#L8
https://github.com/YunoHost/yunohost/blob/unstable/data/templates/postfix/main.cf#L144

**Comment by zamentur** [comment]
Maybe there is a permission issue
ls -l /var/spool/postfix/run/
ls -l /var/spool/postfix/run/rmilter

In this case a yunohost service regen-conf rmilter --force should fix it

**Comment by polytan02** [comment]
ls -l /var/spool/postfix/run/
total 4
drwxrwxr-x 2 postfix _rmilter 4096 Feb 10 18:14 rmilter/

ls -l /var/spool/postfix/run/rmilter
total 0
srwxrwxrwx 1 _rmilter _rmilter 0 Feb 10 18:14 rmilter.sock=

Also, I did a yunohost service regen-conf rmilter --force and the postfix/smtpd[5087]: warning: connect to Milter service unix:/run/rmilter/rmilter.sock: Connection refused
 is still there :/

**Comment by zamentur** [comment]
What is the hardware (arm ? x64? raspberry pi, olimex ??)
Which installation method and which image have you used ?

**Comment by polytan02** [comment]
X86-64 scaleway vps, installation via git clone et lancement du scritp d'installation tel que décrit dans la doc.

**Comment by opi** [comment]
here is my setup: 
```
root@donny:~# ls -l /var/spool/postfix/run/
total 4
drwxrwxr-x 2 postfix _rmilter 4096 janv. 11 21:55 rmilter
root@donny:~# ls -l /var/spool/postfix/run/rmilter
total 0
srwxrwxrwx 1 postfix _rmilter 0 janv. 11 21:55 rmilter.sock
```
and in `/var/log/mail.log` I see: 
```
Feb 11 23:50:40 sd-20080 rmilter[28654]: <b45d56ce22>; mlfi_eom: d=*******, s=mail, added DKIM signature
```

I run YunoHost latest testing release (2.5.5), and my "regen-conf" status is clean

**Comment by opi** [comment]
note: x86 hardware, installed on debian 7 with script since ynh 2.2, and now running debian 8 with 2.5.5

**Comment by opi** [comment]
on a vagrant box, running latest unstable : 
```
root@yunohost:~# ls -l /var/spool/postfix/run/rmilter/rmilter.sock
srwxrwxrwx 1 _rmilter _rmilter 0 Jan 31 15:41 /var/spool/postfix/run/rmilter/rmilter.sock
```
can't test to send mail right now :/

**Comment by polytan02** [comment]
So, after some tests with @opi , we seem to understand that : 
- The version of rmilter used on stable is the old version, not the updated one
- For some reason, rmilter.conf.common take precedent of rmilter.conf

If confirmed by others, it would mean that, for short term to be fixed : 
- update rspamd/rmilter to the latest version required by YnH 2.5 (v 1.9.2 I believe ?)
- modify rmilter.conf.common to have the "mail" selector in dkim section (short term !)

On the loinger term, maybe we could consider to have the rmilter configurations in a conf.d folder

**Comment by polytan02** [comment]
Hi,

Today I noticed this file :  rmilter.conf.sysvinit

`sysvinit-specific settings for rmilter
.include /etc/rmilter.conf.common

bind_socket = unix:/run/rmilter/rmilter.sock;

# pidfile - path to pid file
# Default: pidfile = /var/run/rmilter.pid
pidfile = /run/rmilter/rmilter.pid;              `

As you can see, there is only conf.common inserted in it, no other dkim section indicating the selector being "mail".

Do you think debian reads rmilter.conf.sysvinit instead of rmilter.conf ?

**Comment by polytan02** [comment]
This morning I had an update of rspamd. I rebooted the server.
On my side, the connection is still not working :( 

`postfix/smtpd[1811]: warning: connect to Milter service unix:/run/rmilter/rmilter.sock: Connection refused`

**Comment by opi** [comment]
update of rspamd/rmilter failed as I said yesterday; I try to fix them but I have no time today :/

**Comment by opi** [comment]
> Today I noticed this file : rmilter.conf.sysvinit

You can see what configuration file is used by running `systemctl status rmilter.service`

**Comment by polytan02** [comment]
```
root ~ #  systemctl status rmilter.sock
● rmilter.sock.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

**Comment by polytan02** [comment]
```
#systemctl status rmilter.service
● rmilter.service - Another sendmail milter for different mail checks
   Loaded: loaded (/lib/systemd/system/rmilter.service; enabled)
   Active: active (running) since mar. 2017-02-14 11:15:11 GMT; 3min 16s ago
 Main PID: 569 (rmilter)
   CGroup: /system.slice/rmilter.service
           └─569 /usr/sbin/rmilter -c /etc/rmilter.conf -n

févr. 14 11:15:11 domain.tld systemd[1]: Started Another sendmail milter for different mail checks.
févr. 14 11:15:11 domain.tld rmilter[569]: main: starting rmilter version 1.9.2, listen on unix:...ock
févr. 14 11:15:11 domain.tld rmilter[569]: reload_thread: starting...
Hint: Some lines were ellipsized, use -l to show in full.
```



```
Feb 14 11:17:20 domain.tld postfix/smtpd[1648]: connect from mysendingip
Feb 14 11:17:20 domain.tld postfix/smtpd[1648]: Anonymous TLS connection mysendingip: TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits)
Feb 14 11:17:20 domain.tld postfix/smtpd[1648]: warning: connect to Milter service unix:/run/rmilter/rmilter.sock: Connection refused
Feb 14 11:17:20 domain.tld postfix/smtpd[1648]: E50437E242: client=mysendingip, sasl_method=PLAIN, sasl_username=maxime
Feb 14 11:17:21 mcgva postfix/cleanup[1469]: E50437E242: message-id=<20170214111720.4628563.21828.577@domain.tld>
Feb 14 11:17:21 domain.tld postfix/qmgr[1465]: E50437E242: from=<maxime@domain.tld>, size=7665, nrcpt=1 (queue active)
Feb 14 11:17:21 domain.tld postfix/smtp[1652]: Untrusted TLS connection established to domaindest.tld[mydestip]:25: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Feb 14 11:17:21 domain.tld postfix/smtp[1652]: E50437E242: to=<jerry@domaindest.tld>, relay=domaindest.tld[mydestip]:25, delay=0.61, delays=0.29/0/0.15/0.17, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 518D9220F65)
Feb 14 11:17:21 domain.tld postfix/qmgr[1465]: E50437E242: removed
Feb 14 11:17:23 domain.tld postfix/smtpd[1648]: disconnect from mysendingip
```

**Comment by opi** [comment]
Rmilter configuration should be updated to allow custom dkim selector . See https://github.com/YunoHost/yunohost/pull/256

**Pull request merged**
