### PR TITLE
[enh] add dynamic variables to systemd helper

### PR DESCRIPTION
**Pull request by tituspijean**
## The problem

Systemd helper is sad because Nginx and Fail2ban have dynamic variables and not it.
More seriously, I have some apps that require additional variables: `__PORT__` (even 2 ports in one case), `__PATH__` (updated path to work with NodeJS helper), `__FINALPATH__` (working directory)...

We can use the current helper, alter the service file and recalculate its checksum *or* we could have the helper enhanced with those dynamic variables. :)

```
# SCRIPT BEFORE
# Create a dedicated systemd config
ynh_add_systemd_config
ynh_replace_string "__PATH__" "$PATH" "$finalsystemdconf"
ynh_replace_string "__NODEJS_PATH__" "$nodejs_path" "$finalsystemdconf"
ynh_replace_string "__FINAL_PATH__" "$final_path" "$finalsystemdconf"
ynh_store_file_checksum --file="$finalsystemdconf"

systemctl daemon-reload
```

## Solution

Add dynamic variables to systemd helper.
(also fix a typo with double n in "optional")

```
# SCRIPT AFTER
# Create a dedicated systemd config
ynh_add_systemd_config path nodejs_path final_path
```

## PR Status

Tested with success in linked PR in the comments.
Ready to be reviewed.

## How to test

...

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Since you have an use case, could you try the helper on your app ?

**Comment by tituspijean** [comment]
First comment, I notice an inconsistency between `$final_path` and `__FINALPATH__` (this replacement is already implemented in the current helper), see the missing `_` in the middle of the string. This could lead to some confusion.

Then, my tests. I used your fixed code, and renamed the helper to not get confused with the current one.
`ynh_add_systemd_config_vars --others_var 'path nodejs_path'`

I get 
```
2020-04-18 16:16:26,396: DEBUG - + for var_to_replace in $others_var
2020-04-18 16:16:26,396: WARNING - _common.sh: line 86: !var_to_replace: unbound variable
2020-04-18 16:16:26,396: DEBUG - ++ ynh_exit_properly
2020-04-18 16:16:26,397: DEBUG - ++ local exit_code=1
2020-04-18 16:16:26,397: DEBUG - ++ '[' 1 -eq 0 ']'
2020-04-18 16:16:26,397: DEBUG - ++ trap '' EXIT
2020-04-18 16:16:26,397: DEBUG - ++ set +eu
2020-04-18 16:16:26,397: DEBUG - ++ sleep 0.5
2020-04-18 16:16:26,900: DEBUG - ++ type -t ynh_clean_setup
2020-04-18 16:16:26,900: WARNING -
2020-04-18 16:16:26,901: DEBUG - ++ ynh_clean_setup
2020-04-18 16:16:26,901: DEBUG - ++ true
2020-04-18 16:16:26,901: DEBUG - ++ ynh_die
2020-04-18 16:16:26,902: DEBUG - ++ local legacy_args=mc
2020-04-18 16:16:26,902: DEBUG - ++ args_array=([m]=message= [c]=ret_code=)
2020-04-18 16:16:26,902: DEBUG - ++ declare -Ar args_array
2020-04-18 16:16:26,902: DEBUG - ++ local message
2020-04-18 16:16:26,902: DEBUG - ++ local ret_code
2020-04-18 16:16:26,903: DEBUG - ++ ynh_handle_getopts_args
2020-04-18 16:16:26,903: DEBUG - ++ set +x
2020-04-18 16:16:26,903: DEBUG - ++ echo ''
2020-04-18 16:16:26,903: DEBUG - ++ exit 1
2020-04-18 16:16:27,024: ERROR - Could not install ztncui: An error occurred inside the app installation script
```

The args are parsed like this:
```
2020-04-18 16:16:26,189: DEBUG - + ynh_add_systemd_config_vars --others_var 'path nodejs_path'
2020-04-18 16:16:26,189: DEBUG - + local legacy_args=stv
2020-04-18 16:16:26,189: DEBUG - + args_array=([s]=service= [t]=template= [v]=others_var=)
2020-04-18 16:16:26,189: DEBUG - + declare -Ar args_array
2020-04-18 16:16:26,189: DEBUG - + local service
2020-04-18 16:16:26,189: DEBUG - + local template
2020-04-18 16:16:26,189: DEBUG - + local others_var
2020-04-18 16:16:26,189: DEBUG - + ynh_handle_getopts_args --others_var 'path nodejs_path'
2020-04-18 16:16:26,189: DEBUG - + set +x
2020-04-18 16:16:26,189: DEBUG - + service=ztncui
2020-04-18 16:16:26,189: DEBUG - + template=systemd.service
2020-04-18 16:16:26,189: DEBUG - + others_var='path nodejs_path'
2020-04-18 16:16:26,190: DEBUG - + finalsystemdconf=/etc/systemd/system/ztncui.service
```

**Comment by maniackcrudelis** [comment]
Try with  `ynh_add_systemd_config_vars --others_var="path nodejs_path"`

**Comment by tituspijean** [comment]
@maniackcrudelis [Same error](https://ci-apps-dev.yunohost.org/jenkins/view/tituspijean/job/ztncui_ynh%20PR5%20(tituspijean)/1/console)

**Comment by maniackcrudelis** [comment]
> "path nodejs_path"

`path` is not a defined variable in your script.
This argument will replace string by variable with the same name into the file. The variable have to exist, otherwise you get an `unbound variable`

**Comment by tituspijean** [comment]
Correct! Last commit fixes it and confirms that the code works as is.

**Pull request merged**
