### PR TITLE
[fix] Password constrains and checks not behaving properly

### PR DESCRIPTION
**Pull request by alexAubin**
## The problem

`--force-password` not working during postinstall, because there's a call to `tools_adminpw` which also performs a check of the strength. 

## Solution

Pass a new `check_strength` argument to `tools_adminpw` so that we can disable the check if `--force-password` is used.

## PR Status

Yolocomitted, not tested :s 

## How to test

Run a postinstall with a dummy password and `--force-install`

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by alexAubin** [comment]
Tested both fixes and that's working

**Comment by maniackcrudelis** [comment]
Is it "--force-password" or "--force-install" ???
During a scripted post install, I had
```
yunohost: error: unrecognized arguments: --force-password
```
Which also means that our unstable CI will wait again...

**Comment by alexAubin** [comment]
Should be `yunohost tools postinstall --force-password` ? Are you sure the version is >= 3.3 ?

**Comment by maniackcrudelis** [comment]
The script get the install script directly.
Anyway, I'm going to delete the complete directory and restart from scratch.

**Pull request merged**
